name: composite-action
description: "Reusable multiple steps of github action"
inputs:
  workingDirectory:
    description: "The working directory this composite actions will be run from"
    required: true
    default: "~"
runs:
  using: "composite"
  steps: 
    - name: Get current working directory
      run: echo $PWD
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
    - name: First Command
      run: ./sample.sh
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
    - name: Second Command
      run: echo "Executing step 2"
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      