name: composite-action
description: "Reusable multiple steps of github action"
inputs:
  workingDirectory:
    description: "The working directory this composite actions will be run from"
    required: true
    default: "~"
runs:
  using: "composite"
  steps: 
    - name: Go to desired working directory
      run: cd ${{ inputs.workingDirectory }}
    - name: Get current working directory
      run: echo $PWD
      shell: bash
    - name: First Command
      run: echo "Executing step 1"
      shell: bash
    - name: Second Command
      run: echo "Executing step 2"
      shell: bash
      