name: composite-action
description: "Reusable multiple steps of github action"
runs:
  using: "composite"
  steps: 
    - run: echo "Step 1"
      shell: bash
    - run: echo "Step 2"
      shell: bash
      