name: composite-action
description: "Reusable multiple steps of github action"
runs:
  using: "composite"
  steps: 
    - name: List Current Working Directory
      run: ls
      shell: bash
    - name: First Command
      run: echo "Step 1"
      shell: bash
    - name: Second Command
      run: echo "Step 2"
      shell: bash
      