name: Composite Example
on:
  push:
    branches:
      - master
jobs:
  job1: 
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    runs-on: ubuntu-latest
    name: Job 1 Example
    steps:
      - name: Get Current Working Directory
        run: ls
      - id: foo1
        name: Executing Composite Action
        uses: nhatmvo/github-action-composite@v1
  job2:
    runs-on: ubuntu-latest
    name: Job 2 Example
    steps:
      - id: foo2
        uses: nhatmvo/github-action-composite@v1