name: Composite Example
on:
  push:
    branches:
      - master
jobs:
  job1: 
    name: Job 1 Example
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Current Working Directory
        run: echo $PWD
      - name: Executing Composite Action
        uses: nhatmvo/github-action-composite@v1
        with:
          workingDirectory: scripts
  job2:
    runs-on: ubuntu-latest
    name: Job 2 Example
    steps:
      - id: foo2
        uses: nhatmvo/github-action-composite@v1