name: Composite Example
on:
  push:
    branches:
      - master
jobs:
  job1: 
    runs-on: ubuntu-latest
    name: Job 1 Example
    steps:
      - id: foo1
        uses: nhatmvo/github-action-composite@v1
  job2:
    runs-on: ubuntu-latest
    name: Job 2 Example
    steps:
      - id: foo2
        uses: nhatmvo/github-action-composite@v1